version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chatapp
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    restart: unless-stopped
    environment:
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - MONGO_URL=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  chat-service:
    build: ./chat-service
    restart: unless-stopped
    environment:
      - PORT=3002
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - MONGO_URL=mongodb://mongo:27017/chatapp
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    ports:
      - "3002:3002"

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - PORT=3000
      - AUTH_URL=http://localhost:3001
      - CHAT_URL=http://localhost:3002
    depends_on:
      - auth-service
      - chat-service
    ports:
      - "3000:3000"

volumes:
  mongo-data: