---
- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Delete all chat app deployments
      shell: |
        kubectl delete -f /home/ubuntu/mongo-deployment.yaml || true
        kubectl delete -f /home/ubuntu/auth-deployment.yaml || true
        kubectl delete -f /home/ubuntu/chat-deployment.yaml || true
        kubectl delete -f /home/ubuntu/frontend-deployment.yaml || true
      
    - name: Verify deployments are deleted
      shell: kubectl get pods,services
      register: k8s_status
    - debug:
        var: k8s_status.stdout